-- Seed Mock Data for Testing
-- This file adds sample Accounts, Contacts, Opportunities, Proposals, Notes, and Reminders

-- Insert Sample Accounts
INSERT INTO accounts (name, industry, website, phone, email, billing_street, billing_city, billing_state, billing_postal_code, billing_country, description, annual_revenue, number_of_employees, owner_id, status, created_by, updated_by) VALUES
('Acme Corporation', 'Technology', 'https://www.acme-corp.com', '+1-555-0101', 'info@acme-corp.com', '123 Tech Boulevard', 'San Francisco', 'CA', '94105', 'USA', 'Leading technology solutions provider', 50000000.00, 250, (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Global Industries Ltd', 'Manufacturing', 'https://www.global-industries.com', '+1-555-0202', 'contact@global-industries.com', '456 Industrial Park', 'Chicago', 'IL', '60601', 'USA', 'International manufacturing company', 120000000.00, 500, (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('TechStart Solutions', 'Software', 'https://www.techstart.com', '+1-555-0303', 'hello@techstart.com', '789 Innovation Drive', 'Austin', 'TX', '78701', 'USA', 'Startup software development company', 5000000.00, 50, (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('MediCare Systems', 'Healthcare', 'https://www.medicare-systems.com', '+1-555-0404', 'info@medicare-systems.com', '321 Health Avenue', 'Boston', 'MA', '02101', 'USA', 'Healthcare management systems', 75000000.00, 300, (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('FinanceFirst Group', 'Financial Services', 'https://www.financefirst.com', '+1-555-0505', 'contact@financefirst.com', '654 Wall Street', 'New York', 'NY', '10005', 'USA', 'Financial advisory services', 200000000.00, 800, (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1));

-- Insert Sample Contacts
INSERT INTO contacts (first_name, last_name, email, phone, mobile, title, department, account_id, mailing_street, mailing_city, mailing_state, mailing_postal_code, mailing_country, description, owner_id, status, created_by, updated_by) VALUES
('John', 'Smith', 'john.smith@acme-corp.com', '+1-555-1001', '+1-555-1002', 'CEO', 'Executive', (SELECT id FROM accounts WHERE name = 'Acme Corporation' LIMIT 1), '123 Tech Boulevard', 'San Francisco', 'CA', '94105', 'USA', 'Chief Executive Officer', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Sarah', 'Johnson', 'sarah.johnson@acme-corp.com', '+1-555-1003', '+1-555-1004', 'VP of Sales', 'Sales', (SELECT id FROM accounts WHERE name = 'Acme Corporation' LIMIT 1), '123 Tech Boulevard', 'San Francisco', 'CA', '94105', 'USA', 'Vice President of Sales', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Michael', 'Brown', 'michael.brown@global-industries.com', '+1-555-2001', '+1-555-2002', 'Operations Manager', 'Operations', (SELECT id FROM accounts WHERE name = 'Global Industries Ltd' LIMIT 1), '456 Industrial Park', 'Chicago', 'IL', '60601', 'USA', 'Operations Manager', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Emily', 'Davis', 'emily.davis@techstart.com', '+1-555-3001', '+1-555-3002', 'CTO', 'Technology', (SELECT id FROM accounts WHERE name = 'TechStart Solutions' LIMIT 1), '789 Innovation Drive', 'Austin', 'TX', '78701', 'USA', 'Chief Technology Officer', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('David', 'Wilson', 'david.wilson@medicare-systems.com', '+1-555-4001', '+1-555-4002', 'Director of IT', 'IT', (SELECT id FROM accounts WHERE name = 'MediCare Systems' LIMIT 1), '321 Health Avenue', 'Boston', 'MA', '02101', 'USA', 'IT Director', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Lisa', 'Anderson', 'lisa.anderson@financefirst.com', '+1-555-5001', '+1-555-5002', 'CFO', 'Finance', (SELECT id FROM accounts WHERE name = 'FinanceFirst Group' LIMIT 1), '654 Wall Street', 'New York', 'NY', '10005', 'USA', 'Chief Financial Officer', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Robert', 'Taylor', 'robert.taylor@acme-corp.com', '+1-555-1005', '+1-555-1006', 'Marketing Director', 'Marketing', (SELECT id FROM accounts WHERE name = 'Acme Corporation' LIMIT 1), '123 Tech Boulevard', 'San Francisco', 'CA', '94105', 'USA', 'Marketing Director', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Jennifer', 'Martinez', 'jennifer.martinez@global-industries.com', '+1-555-2003', '+1-555-2004', 'HR Manager', 'Human Resources', (SELECT id FROM accounts WHERE name = 'Global Industries Ltd' LIMIT 1), '456 Industrial Park', 'Chicago', 'IL', '60601', 'USA', 'Human Resources Manager', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1));

-- Insert Sample Opportunities
INSERT INTO opportunities (name, description, account_id, contact_id, stage, probability, amount, expected_close_date, owner_id, status, created_by, updated_by) VALUES
('Enterprise Software License', 'Large enterprise software license deal with Acme Corporation', (SELECT id FROM accounts WHERE name = 'Acme Corporation' LIMIT 1), (SELECT id FROM contacts WHERE email = 'john.smith@acme-corp.com' LIMIT 1), 'NEGOTIATION', 75, 500000.00, DATE_ADD(NOW(), INTERVAL 30 DAY), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Cloud Migration Project', 'Cloud infrastructure migration project for Global Industries', (SELECT id FROM accounts WHERE name = 'Global Industries Ltd' LIMIT 1), (SELECT id FROM contacts WHERE email = 'michael.brown@global-industries.com' LIMIT 1), 'PROPOSAL', 60, 250000.00, DATE_ADD(NOW(), INTERVAL 45 DAY), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Startup Partnership', 'Technology partnership opportunity with TechStart Solutions', (SELECT id FROM accounts WHERE name = 'TechStart Solutions' LIMIT 1), (SELECT id FROM contacts WHERE email = 'emily.davis@techstart.com' LIMIT 1), 'QUALIFICATION', 40, 100000.00, DATE_ADD(NOW(), INTERVAL 60 DAY), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Healthcare System Upgrade', 'Major system upgrade for MediCare Systems', (SELECT id FROM accounts WHERE name = 'MediCare Systems' LIMIT 1), (SELECT id FROM contacts WHERE email = 'david.wilson@medicare-systems.com' LIMIT 1), 'PROSPECTING', 25, 750000.00, DATE_ADD(NOW(), INTERVAL 90 DAY), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'ACTIVE', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Financial Services Contract', 'Long-term contract with FinanceFirst Group', (SELECT id FROM accounts WHERE name = 'FinanceFirst Group' LIMIT 1), (SELECT id FROM contacts WHERE email = 'lisa.anderson@financefirst.com' LIMIT 1), 'CLOSED_WON', 100, 1200000.00, DATE_SUB(NOW(), INTERVAL 5 DAY), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), 'WON', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1));

-- Insert Sample Proposals
INSERT INTO proposals (title, description, opportunity_id, account_id, contact_id, proposal_number, amount, currency, valid_until, status, owner_id, created_by, updated_by) VALUES
('Enterprise Software License Proposal', 'Comprehensive proposal for enterprise software license', (SELECT id FROM opportunities WHERE name = 'Enterprise Software License' LIMIT 1), (SELECT id FROM accounts WHERE name = 'Acme Corporation' LIMIT 1), (SELECT id FROM contacts WHERE email = 'john.smith@acme-corp.com' LIMIT 1), 'PROP-2024-001', 500000.00, 'USD', DATE_ADD(NOW(), INTERVAL 30 DAY), 'SENT', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Cloud Migration Services Proposal', 'Detailed proposal for cloud migration services', (SELECT id FROM opportunities WHERE name = 'Cloud Migration Project' LIMIT 1), (SELECT id FROM accounts WHERE name = 'Global Industries Ltd' LIMIT 1), (SELECT id FROM contacts WHERE email = 'michael.brown@global-industries.com' LIMIT 1), 'PROP-2024-002', 250000.00, 'USD', DATE_ADD(NOW(), INTERVAL 45 DAY), 'REVIEWED', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Technology Partnership Proposal', 'Partnership proposal for TechStart Solutions', (SELECT id FROM opportunities WHERE name = 'Startup Partnership' LIMIT 1), (SELECT id FROM accounts WHERE name = 'TechStart Solutions' LIMIT 1), (SELECT id FROM contacts WHERE email = 'emily.davis@techstart.com' LIMIT 1), 'PROP-2024-003', 100000.00, 'USD', DATE_ADD(NOW(), INTERVAL 60 DAY), 'DRAFT', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Healthcare System Upgrade Proposal', 'Proposal for healthcare system upgrade', NULL, (SELECT id FROM accounts WHERE name = 'MediCare Systems' LIMIT 1), (SELECT id FROM contacts WHERE email = 'david.wilson@medicare-systems.com' LIMIT 1), 'PROP-2024-004', 750000.00, 'USD', DATE_ADD(NOW(), INTERVAL 90 DAY), 'APPROVED', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Financial Services Contract Proposal', 'Long-term contract proposal', NULL, (SELECT id FROM accounts WHERE name = 'FinanceFirst Group' LIMIT 1), (SELECT id FROM contacts WHERE email = 'lisa.anderson@financefirst.com' LIMIT 1), 'PROP-2024-005', 1200000.00, 'USD', DATE_SUB(NOW(), INTERVAL 5 DAY), 'ACCEPTED', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1));

-- Insert Sample Notes
INSERT INTO notes (title, content, note_type, contact_id, account_id, created_by, updated_by) VALUES
('Initial Meeting with John Smith', 'Had a productive initial meeting with John Smith, CEO of Acme Corporation. Discussed their software needs and potential partnership opportunities.', 'contact', (SELECT id FROM contacts WHERE email = 'john.smith@acme-corp.com' LIMIT 1), NULL, (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Follow-up Call with Sarah Johnson', 'Follow-up call regarding the sales proposal. Sarah showed strong interest and requested additional information.', 'contact', (SELECT id FROM contacts WHERE email = 'sarah.johnson@acme-corp.com' LIMIT 1), NULL, (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Acme Corporation - Company Overview', 'Acme Corporation is a leading technology company with 250 employees. They are looking to expand their software infrastructure.', 'account', NULL, (SELECT id FROM accounts WHERE name = 'Acme Corporation' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Global Industries - Project Discussion', 'Discussed the cloud migration project with Michael Brown. They need a comprehensive solution for their manufacturing operations.', 'account', NULL, (SELECT id FROM accounts WHERE name = 'Global Industries Ltd' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('TechStart Solutions - Partnership Opportunity', 'Emily Davis, CTO, expressed interest in a technology partnership. They are a growing startup with innovative solutions.', 'account', NULL, (SELECT id FROM accounts WHERE name = 'TechStart Solutions' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('MediCare Systems - System Requirements', 'David Wilson provided detailed requirements for the healthcare system upgrade. They need HIPAA-compliant solutions.', 'account', NULL, (SELECT id FROM accounts WHERE name = 'MediCare Systems' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1));

-- Insert Sample Reminders
INSERT INTO reminders (title, description, reminder_type, contact_id, account_id, due_date, priority, status, created_by, updated_by) VALUES
('Follow up with John Smith', 'Schedule follow-up meeting with John Smith to discuss the enterprise software proposal', 'contact', (SELECT id FROM contacts WHERE email = 'john.smith@acme-corp.com' LIMIT 1), NULL, DATE_ADD(NOW(), INTERVAL 3 DAY), 'HIGH', 'PENDING', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Send proposal to Sarah Johnson', 'Send the detailed sales proposal to Sarah Johnson at Acme Corporation', 'contact', (SELECT id FROM contacts WHERE email = 'sarah.johnson@acme-corp.com' LIMIT 1), NULL, DATE_ADD(NOW(), INTERVAL 1 DAY), 'HIGH', 'PENDING', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Review contract with Acme Corporation', 'Review and finalize the contract terms with Acme Corporation', 'account', NULL, (SELECT id FROM accounts WHERE name = 'Acme Corporation' LIMIT 1), DATE_ADD(NOW(), INTERVAL 7 DAY), 'MEDIUM', 'PENDING', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Prepare presentation for Global Industries', 'Prepare presentation for the cloud migration project proposal', 'account', NULL, (SELECT id FROM accounts WHERE name = 'Global Industries Ltd' LIMIT 1), DATE_ADD(NOW(), INTERVAL 5 DAY), 'MEDIUM', 'PENDING', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Schedule demo with TechStart Solutions', 'Schedule product demonstration for TechStart Solutions partnership opportunity', 'account', NULL, (SELECT id FROM accounts WHERE name = 'TechStart Solutions' LIMIT 1), DATE_ADD(NOW(), INTERVAL 10 DAY), 'LOW', 'PENDING', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Quarterly review with MediCare Systems', 'Quarterly business review meeting with MediCare Systems', 'account', NULL, (SELECT id FROM accounts WHERE name = 'MediCare Systems' LIMIT 1), DATE_ADD(NOW(), INTERVAL 14 DAY), 'MEDIUM', 'PENDING', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1)),
('Contract renewal discussion with FinanceFirst', 'Discuss contract renewal terms with FinanceFirst Group', 'account', NULL, (SELECT id FROM accounts WHERE name = 'FinanceFirst Group' LIMIT 1), DATE_ADD(NOW(), INTERVAL 20 DAY), 'LOW', 'PENDING', (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1), (SELECT id FROM users WHERE email = 'admin@crm.com' LIMIT 1));
